baseURL = 'https://programmerraja.github.io/blog'
languageCode = 'en-us'
title = 'programmerraja blog'
theme = 'blog'
publishDir='public/blog'

enableEmoji = true

[params]
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' b

[menu]
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/post/'
    weight = 20
 
  [[menu.main]]
    pageRef="resources"
    name = 'Resources'
    url = '/resources/'
    weight = 40
  
   [[menu.main]]
    pageRef="notes"
    name = 'Notes'
    url = '/notes/'
    weight = 50

  [[menu.main]]
    pageRef="whoami"
    name = 'Portfolio'
    url = 'https://programmerraja.github.io/'
    weight = 50

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 
		endLevel = 4 
		ordered = true 

[params.author]
    avatar = "myself.jpeg"
    intro = "K.Boopathi"
    name = "K.Boopathi"
    description = "Exploring diverse tech realms, I'm a curious programmer crafting blogs on web dev and sharing learning resources! 🚀 Dive into my world of code exploration and innovation!"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/programmerraja"

[[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/programmerraja"

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/programmerraja/"

[[params.socialIcons]]
    name = "Rss"
    url = "index.xml"


